#Still depends on triggering default gh deploy actions 
name: Zola Build
description: Build (and/or deploy) a getzola/zola site
author: Kenzi Connor
branding:
  icon: cast
  color: purple
inputs:
  root:
    description: Directory to use as root of project 
    required: false
    default: '.'
    type: string
  config:
    description: Path to a config file other than config.toml in the root of project
    required: false
    default: 'config.toml'
    type: string
  base-url:
    description: Force the base URL to be that value (defaults to the one in config)
    required: false
    default: ''
    type: string
  drafts:
    description: Include drafts when loading the site
    required: false
    default: false
    type: boolean
  output-dir:
    description: Outputs the generated site in the given path (by default 'public' dir in project root)
    required: false
    default: 'public'
    type: string
  force:
    description: Force building the site even if output directory is non-empty
    required: false
    default: false
    type: boolean
  deploy:
    description: Push to GitHub-Pages using JamesIves/github-pages-deploy-action defaults
    required: false
    default: true
    type: boolean
  check:
    description: Check external links with `zola check`
    required: false
    default: true
    type: boolean


runs:
  using: composite
  steps:
    - name: output variables
      shell: bash
      run: echo '${{toJSON(inputs)}}'
    - name: build flags
      shell: bash
      run: |
        echo "base_command=zola -r ${{inputs.root}} -c ${{inputs.config}}" >> $GITHUB_ENV
        if ${{ inputs.drafts }}; then
          echo "drafts_flag=--draft" >> $GITHUB_ENV
        fi
        build_flags='-o ${{inputs.output-dir}}'
        if ${{inputs.force}}; then
          build_flags="-o $build_flags --force"
        fi
        echo "build_flags=$build_flags" >> $GITHUB_ENV
    - uses: knzai/zola-cli@idempotent_install
    - name: zola check
      if: inputs.check
      shell: bash
      run: $base_command check $drafts_flag
    - name: zola build
      shell: bash
      run: $base_command build $drafts_flag $build_flags
    - name: Deploy 🚀
      if: inputs.deploy
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: ${{inputs.root}}/${{inputs.output-dir}}
      
