on: push
name: Test Zola CLI
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
        submodules: true
        ref: site
    - uses: knzai/zola-build@main
        